version: '3.8'
services:
  ollama:
    image: ollama/ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    volumes:
      - /opt/ollama/data:/root/.ollama
      - /opt/ollama/var:/var/lib/ollama
    ports:
      - 31337:11434
    container_name: ollama
    restart: unless-stopped

volumes:
  ollama:
    external:
      name: ollama